// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestControlAPI.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int RestaurantId { get; set; }

    public int? TableId { get; set; }

    public int? ReservationId { get; set; }

    public int? StaffId { get; set; }

    public DateTime? OrderDate { get; set; }

    public string Status { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Reservation Reservation { get; set; }

    public virtual Restaurant Restaurant { get; set; }

    public virtual Staff Staff { get; set; }

    public virtual Table Table { get; set; }
}