// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestControlAPI.Models;

public partial class Person
{
    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Department { get; set; }
}