// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestControlAPI.Models;

public partial class Plan
{
    public int PlanId { get; set; }

    public string Name { get; set; }

    public decimal MonthlyPrice { get; set; }

    public decimal ReservationCommission { get; set; }

    public virtual ICollection<RestaurantSubscription> RestaurantSubscriptions { get; set; } = new List<RestaurantSubscription>();
}