// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestControlAPI.Models;

public partial class PlatformEarning
{
    public int EarningId { get; set; }

    public int RestaurantId { get; set; }

    public int? ReservationId { get; set; }

    public decimal Amount { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Reservation Reservation { get; set; }

    public virtual Restaurant Restaurant { get; set; }
}