// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestControlAPI.Models;

public partial class ReservationTable
{
    public int ReservationTableId { get; set; }

    public int ReservationId { get; set; }

    public int TableId { get; set; }

    public virtual Reservation Reservation { get; set; }

    public virtual Table Table { get; set; }
}