// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestControlAPI.Models;

public partial class Reservation
{
    public int ReservationId { get; set; }

    public int RestaurantId { get; set; }

    public int CustomerId { get; set; }

    public DateTime ReservationDate { get; set; }

    public int NumberOfPeople { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PlatformEarning> PlatformEarnings { get; set; } = new List<PlatformEarning>();

    public virtual ICollection<ReservationTable> ReservationTables { get; set; } = new List<ReservationTable>();

    public virtual Restaurant Restaurant { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}