// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestControlAPI.Models;

public partial class Restaurant
{
    public int RestaurantId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public int OwnerId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual User Owner { get; set; }

    public virtual ICollection<PlatformEarning> PlatformEarnings { get; set; } = new List<PlatformEarning>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual ICollection<RestaurantImage> RestaurantImages { get; set; } = new List<RestaurantImage>();

    public virtual ICollection<RestaurantSubscription> RestaurantSubscriptions { get; set; } = new List<RestaurantSubscription>();

    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();

    public virtual ICollection<Table> Tables { get; set; } = new List<Table>();
}