// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestControlAPI.Models;

public partial class RestaurantSubscription
{
    public int SubscriptionId { get; set; }

    public int RestaurantId { get; set; }

    public int PlanId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public bool? IsActive { get; set; }

    public virtual Plan Plan { get; set; }

    public virtual Restaurant Restaurant { get; set; }
}