// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestControlAPI.Models;

public partial class Staff
{
    public int StaffId { get; set; }

    public int RestaurantId { get; set; }

    public int UserId { get; set; }

    public string Position { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Restaurant Restaurant { get; set; }

    public virtual User User { get; set; }
}