// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RestControlAPI.Models;

public partial class Table
{
    public int TableId { get; set; }

    public int RestaurantId { get; set; }

    public int TableNumber { get; set; }

    public int Capacity { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<ReservationTable> ReservationTables { get; set; } = new List<ReservationTable>();

    public virtual Restaurant Restaurant { get; set; }
}